name: maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Build with Maven
      run: sudo apt-get update && sudo apt-get install -yq libgfortran3 && mvn -B package --file pom.xml
